# BEE2041 Empirical Project: What property and location factors determine Airbnb listing prices in London?
## 02_cleaning

In [113]:
# Import Libraries
import pandas as pd
import numpy as np

# Import Data
df = pd.read_csv("../data/raw/london.csv")

# View first 5 rows
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,13913,https://www.airbnb.com/rooms/13913,20250914034649,2025-09-16,city scrape,Holiday London DB Room Let-on going,My bright double bedroom with a large window h...,Finsbury Park is a friendly melting pot commun...,https://a0.muscache.com/pictures/miso/Hosting-...,54730,...,4.87,4.78,4.78,NaN,f,2,1,1,0,0.30
1,15400,https://www.airbnb.com/rooms/15400,20250914034649,2025-09-16,city scrape,Bright Chelsea Apartment. Chelsea!,Lots of windows and light. St Luke's Gardens ...,It is Chelsea.,https://a0.muscache.com/pictures/428392/462d26...,60302,...,4.84,4.93,4.74,NaN,f,1,1,0,0,0.51
2,17402,https://www.airbnb.com/rooms/17402,20250914034649,2025-09-16,city scrape,Very Central Modern 3-Bed/2 Bath By Oxford St W1,"You'll have a great time in this beautiful, cl...","Fitzrovia is a very desirable trendy, arty and...",https://a0.muscache.com/pictures/39d5309d-fba7...,67564,...,4.72,4.89,4.61,NaN,f,2,2,0,0,0.32
3,24328,https://www.airbnb.com/rooms/24328,20250914034649,2025-09-18,previous scrape,Battersea live/work artist house,"Artist house by SW Battersea Park, bright high...","- Battersea is a quiet family area, easy acces...",https://a0.muscache.com/pictures/9194b40f-c627...,41759,...,4.93,4.60,4.65,NaN,f,1,1,0,0,0.53
4,36274,https://www.airbnb.com/rooms/36274,20250914034649,2025-09-15,city scrape,Bright 1 bedroom apt off brick lane in Shoreditch,*Update June '25- Pump Installed to improve wa...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,133271,...,4.46,4.85,4.54,NaN,t,2,2,0,0,0.09

In [114]:
# View Columns
df.columns

# List Desired Columns
cols = [
    "price",
    "accommodates",
    "bedrooms",
    "beds",
    "bathrooms",
    "property_type",
    "room_type",
    "latitude",
    "longitude",
    "review_scores_rating",
    "number_of_reviews",
    "reviews_per_month",
    "availability_365",
    "host_is_superhost",
    "host_listings_count",
    "instant_bookable"
]

# Create new DataFrame with only the desired columns
df_1 = df[cols].copy()

# View first 5 rows of new DataFrame
df_1.head()

,price,accommodates,bedrooms,beds,bathrooms,property_type,room_type,latitude,longitude,review_scores_rating,number_of_reviews,reviews_per_month,availability_365,host_is_superhost,host_listings_count,instant_bookable
0,$70.00,1,1.0,1.0,1.0,Private room in rental unit,Private room,51.56861,-0.11270,4.85,55,0.30,331,t,2.0,f
1,$149.00,2,1.0,1.0,1.0,Entire rental unit,Entire home/apt,51.48780,-0.16813,4.80,97,0.51,199,f,1.0,f
2,$411.00,6,3.0,3.0,2.0,Entire rental unit,Entire home/apt,51.52195,-0.14094,4.77,56,0.32,80,t,3.0,f
3,NaN,2,1.0,NaN,NaN,Entire townhouse,Entire home/apt,51.47072,-0.16266,4.90,95,0.53,294,f,1.0,f
4,$210.00,4,1.0,0.0,1.0,Entire condo,Entire home/apt,51.52322,-0.06979,4.53,15,0.09,323,f,3.0,t

In [115]:
# Change price from a string to a float
df_1["price"] = df_1["price"].replace(r"[\$,]", "", regex=True).astype(float)

# View change
df_1["price"].head()

0     70.0
1    149.0
2    411.0
3      NaN
4    210.0
Name: price, dtype: float64

In [116]:
# Check for missing values
print(df_1.isnull().sum())

# Drop rows with missing values
df_1 = df_1.dropna()

# Check for missing values again
print(df_1.isnull().sum())

price                   34908
accommodates                0
bedrooms                12775
beds                    34920
bathrooms               34846
property_type               0
room_type                   0
latitude                    0
longitude                   0
review_scores_rating    24122
number_of_reviews           0
reviews_per_month       24122
availability_365            0
host_is_superhost        1766
host_listings_count        41
instant_bookable            0
dtype: int64
price                   0
accommodates            0
bedrooms                0
beds                    0
bathrooms               0
property_type           0
room_type               0
latitude                0
longitude               0
review_scores_rating    0
number_of_reviews       0
reviews_per_month       0
availability_365        0
host_is_superhost       0
host_listings_count     0
instant_bookable        0
dtype: int64

In [117]:
# Fix boolean variables
df_1["host_is_superhost"] = df_1["host_is_superhost"].map({"t": 1, "f": 0})
df_1["instant_bookable"] = df_1["instant_bookable"].map({"t": 1, "f": 0})

# View first 10 rows
df_1.head(10)

,price,accommodates,bedrooms,beds,bathrooms,property_type,room_type,latitude,longitude,review_scores_rating,number_of_reviews,reviews_per_month,availability_365,host_is_superhost,host_listings_count,instant_bookable
0,70.0,1,1.0,1.0,1.0,Private room in rental unit,Private room,51.56861,-0.11270,4.85,55,0.30,331,1,2.0,0
1,149.0,2,1.0,1.0,1.0,Entire rental unit,Entire home/apt,51.48780,-0.16813,4.80,97,0.51,199,0,1.0,0
2,411.0,6,3.0,3.0,2.0,Entire rental unit,Entire home/apt,51.52195,-0.14094,4.77,56,0.32,80,1,3.0,0
4,210.0,4,1.0,0.0,1.0,Entire condo,Entire home/apt,51.52322,-0.06979,4.53,15,0.09,323,0,3.0,1
5,280.0,5,3.0,3.0,1.5,Entire townhouse,Entire home/apt,51.48145,-0.28107,4.80,116,0.64,324,0,1.0,0
6,90.0,2,1.0,1.0,0.0,Private room in home,Private room,51.58478,-0.16057,4.87,730,4.00,289,1,2.0,1
7,61.0,2,1.0,1.0,1.0,Private room in townhouse,Private room,51.50681,-0.23345,4.77,387,2.14,9,1,3.0,0
8,340.0,7,4.0,4.0,2.0,Entire townhouse,Entire home/apt,51.50701,-0.23362,4.83,42,0.26,317,1,3.0,0
9,49.0,2,1.0,1.0,1.0,Private room in rental unit,Private room,51.47860,-0.06114,4.97,72,1.06,172,1,1.0,0
11,213.0,4,2.0,3.0,1.0,Entire rental unit,Entire home/apt,51.61492,-0.25632,4.50,25,0.15,162,0,1.0,0

In [118]:
# Check number of properties priced above $1000
print(len(df_1[df_1["price"]>1000]))

# Remove these extreme outliers
df_1 = df_1[df_1["price"] <= 1000]

# Check number of properties priced above $1000 again
print(len(df_1[df_1["price"]>1000]))

321
0

In [119]:
# Simplify property_type
df_1["property_type_simple"] = df_1["property_type"].apply(
    lambda x: "Entire" if "Entire" in x
    else "Private Room" if "Private room" in x
    else "Shared Room" if "Shared room" in x
    else "Other"
)

# Drop original property_type column
df_1 = df_1.drop("property_type", axis=1)

# View first 5 rows
df_1.head()

,price,accommodates,bedrooms,beds,bathrooms,room_type,latitude,longitude,review_scores_rating,number_of_reviews,reviews_per_month,availability_365,host_is_superhost,host_listings_count,instant_bookable,property_type_simple
0,70.0,1,1.0,1.0,1.0,Private room,51.56861,-0.11270,4.85,55,0.30,331,1,2.0,0,Private Room
1,149.0,2,1.0,1.0,1.0,Entire home/apt,51.48780,-0.16813,4.80,97,0.51,199,0,1.0,0,Entire
2,411.0,6,3.0,3.0,2.0,Entire home/apt,51.52195,-0.14094,4.77,56,0.32,80,1,3.0,0,Entire
4,210.0,4,1.0,0.0,1.0,Entire home/apt,51.52322,-0.06979,4.53,15,0.09,323,0,3.0,1,Entire
5,280.0,5,3.0,3.0,1.5,Entire home/apt,51.48145,-0.28107,4.80,116,0.64,324,0,1.0,0,Entire

In [120]:
# Encode category columns
df_1 = pd.get_dummies(df_1, columns=[
    "property_type_simple",
    "room_type"
], drop_first=True, dtype=int)

# Show first 10 rows
df_1.head(10)

,price,accommodates,bedrooms,beds,bathrooms,latitude,longitude,review_scores_rating,number_of_reviews,reviews_per_month,availability_365,host_is_superhost,host_listings_count,instant_bookable,property_type_simple_Other,property_type_simple_Private Room,property_type_simple_Shared Room,room_type_Hotel room,room_type_Private room,room_type_Shared room
0,70.0,1,1.0,1.0,1.0,51.56861,-0.11270,4.85,55,0.30,331,1,2.0,0,0,1,0,0,1,0
1,149.0,2,1.0,1.0,1.0,51.48780,-0.16813,4.80,97,0.51,199,0,1.0,0,0,0,0,0,0,0
2,411.0,6,3.0,3.0,2.0,51.52195,-0.14094,4.77,56,0.32,80,1,3.0,0,0,0,0,0,0,0
4,210.0,4,1.0,0.0,1.0,51.52322,-0.06979,4.53,15,0.09,323,0,3.0,1,0,0,0,0,0,0
5,280.0,5,3.0,3.0,1.5,51.48145,-0.28107,4.80,116,0.64,324,0,1.0,0,0,0,0,0,0,0
6,90.0,2,1.0,1.0,0.0,51.58478,-0.16057,4.87,730,4.00,289,1,2.0,1,0,1,0,0,1,0
7,61.0,2,1.0,1.0,1.0,51.50681,-0.23345,4.77,387,2.14,9,1,3.0,0,0,1,0,0,1,0
8,340.0,7,4.0,4.0,2.0,51.50701,-0.23362,4.83,42,0.26,317,1,3.0,0,0,0,0,0,0,0
9,49.0,2,1.0,1.0,1.0,51.47860,-0.06114,4.97,72,1.06,172,1,1.0,0,0,1,0,0,1,0
11,213.0,4,2.0,3.0,1.0,51.61492,-0.25632,4.50,25,0.15,162,0,1.0,0,0,0,0,0,0,0

In [132]:
# Log transform price
df_1["log_price"] = np.log(df_1["price"])

# Check DataFrame
print(df_1.info())
print(df_1.describe())

<class 'pandas.core.frame.DataFrame'>
Index: 46390 entries, 0 to 96867
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   price                              46390 non-null  float64
 1   accommodates                       46390 non-null  int64
 2   bedrooms                           46390 non-null  float64
 3   beds                               46390 non-null  float64
 4   bathrooms                          46390 non-null  float64
 5   latitude                           46390 non-null  float64
 6   longitude                          46390 non-null  float64
 7   review_scores_rating               46390 non-null  float64
 8   number_of_reviews                  46390 non-null  int64
 9   reviews_per_month                  46390 non-null  float64
 10  availability_365                   46390 non-null  int64
 11  host_is_superhost                  46390 non-null  int64
 12  host_listings_count                46390 non-null  float64
 13  instant_bookable                   46390 non-null  int64
 14  property_type_simple_Other         46390 non-null  int64
 15  property_type_simple_Private Room  46390 non-null  int64
 16  property_type_simple_Shared Room   46390 non-null  int64
 17  room_type_Hotel room               46390 non-null  int64
 18  room_type_Private room             46390 non-null  int64
 19  room_type_Shared room              46390 non-null  int64
 20  log_price                          46390 non-null  float64
dtypes: float64(10), int64(11)
memory usage: 7.8 MB
None
              price  accommodates      bedrooms          beds     bathrooms  \
count  46390.000000  46390.000000  46390.000000  46390.000000  46390.000000
mean     165.860293      3.505691      1.522979      1.946626      1.333854
std      134.780096      2.132426      0.944321      1.366142      0.635381
min       10.000000      1.000000      0.000000      0.000000      0.000000
25%       75.000000      2.000000      1.000000      1.000000      1.000000
50%      130.000000      3.000000      1.000000      2.000000      1.000000
75%      207.000000      4.000000      2.000000      2.000000      1.500000
max     1000.000000     16.000000     12.000000     24.000000     12.500000

           latitude     longitude  review_scores_rating  number_of_reviews  \
count  46390.000000  46390.000000          46390.000000       46390.000000
mean      51.509342     -0.131692              4.671137          34.786333
std        0.049056      0.102481              0.513558          64.455808
min       51.295937     -0.496760              1.000000           1.000000
25%       51.485800     -0.192300              4.570000           4.000000
50%       51.513340     -0.133781              4.820000          13.000000
75%       51.537060     -0.072502              5.000000          37.000000
max       51.682630      0.278960              5.000000        1902.000000

       reviews_per_month  ...  host_is_superhost  host_listings_count  \
count       46390.000000  ...       46390.000000         46390.000000
mean            1.279052  ...           0.286419            25.263505
std             1.412651  ...           0.452093           149.633220
min             0.010000  ...           0.000000             1.000000
25%             0.330000  ...           0.000000             1.000000
50%             0.820000  ...           0.000000             3.000000
75%             1.720000  ...           1.000000            15.000000
max            36.960000  ...           1.000000          5469.000000

       instant_bookable  property_type_simple_Other  \
count      46390.000000                46390.000000
mean           0.370554                    0.014098
std            0.482958                    0.117896
min            0.000000                    0.000000
25%            0.000000                    0.000000
50%            0.000000                    0.000000
75%            1.000000                    0.000000
max            1.000000                    1.000000

       property_type_simple_Private Room  property_type_simple_Shared Room  \
count                       46390.000000                      46390.000000
mean                            0.297758                          0.002393
std                             0.457278                          0.048858
min                             0.000000                          0.000000
25%                             0.000000                          0.000000
50%                             0.000000                          0.000000
75%                             1.000000                          0.000000
max                             1.000000                          1.000000

       room_type_Hotel room  room_type_Private room  room_type_Shared room  \
count          46390.000000            46390.000000           46390.000000
mean               0.001035                0.307329               0.002393
std                0.032151                0.461392               0.048858
min                0.000000                0.000000               0.000000
25%                0.000000                0.000000               0.000000
50%                0.000000                0.000000               0.000000
75%                0.000000                1.000000               0.000000
max                1.000000                1.000000               1.000000

          log_price
count  46390.000000
mean       4.849999
std        0.719141
min        2.302585
25%        4.317488
50%        4.867534
75%        5.332719
max        6.907755

[8 rows x 21 columns]

In [134]:
# Save cleaned DataFrame
df_1.to_csv("../data/cleaned/london_clean.csv", index=False)